name: example
description: A project used to demo the Config Generator
version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.10
  config_generator:
    path: ..